schemaVersion: 2.1.0
metadata:
  name: LnL Test
projects:
  - name: python-example
    git:
      remotes:
        origin: https://github.com/redhat-developer/app-services-sdk-core.git

  - name: nodejs-example
    git:
      remotes:
        origin: https://github.com/redhat-developer/devfile-sample.git
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.8
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      memoryLimit: '2Gi'
      memoryRequest: '1Gi'
      cpuLimit: '2'
      cpuRequest: '1'
      mountSources: true
  - name: venv
    volume:
      size: 1G

  - name: nodejs
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.8
      memoryLimit: '2Gi'
      memoryRequest: '1Gi'
      cpuLimit: '2'
      cpuRequest: '1'
      mountSources: true

  - name: jupyter
    plugin:
      id: Jupyter
